### ISSUE TITLE
Permission to download the checkpoint.

### ISSUE THREAD

**Issue by SwingWillwow** [zhiqic/GSRFormer#6]
Hi! This is excellent work, and I am trying to test its performance on some novel cases. However, I can not download the checkpoint from the link. Google Drive informs me that I am not allowed to download this file. Would you please offer permission to download the model checkpoint?

**Comment by zhiqic** [comment]
I have double-checked the permissions, and you can try downloading the file using a VPN. I am able to download it from my end, just as I showed you in the screenshot earlier.

**Comment by SwingWillwow** [comment]
> I have double-checked the permissions, and you can try downloading the file using a VPN. I am able to download it from my end, just as I showed you in the screenshot earlier.

Actually, I visit the google drive page using a VPN. However, it did not work.
![image](https://github.com/zhiqic/GSRFormer/assets/25071486/c1f66b09-76d5-40c4-8d76-c29d77b25dcc)
May you directly share the checkpoint using the email? 
My email is swingwillow@gmail.com
Thank you!
