### ISSUE TITLE
Any ground truths of role labels are used in eval/test stage?

### ISSUE THREAD

**Issue by jiaminglei-cs** [zhiqic/GSRFormer#8]
Any ground truths of role labels are used in eval/test stage?

Thanks for this wonderful work. However, when I run the original codes provided by you, I find that ground truths of role labels are used in eval/test stage. Specifically, in transformer.py, the variable "inference" is "False" when the codes run to line 94, so that the labels of role will be used to predict. Besides, if I block the ground truths of role labels, the test performance will drop significantly. I am not sure if this is the result of the code running properly. I would appreciate it if you could address my concern.

**Comment by jiaminglei-cs** [comment]
您的邮件已收到，谢谢！

**Comment by zhiqic** [comment]
To clarify the issue, ground truth labels are only used to evaluate the performance.
